apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: daemonset-manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
