---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - power.cluster-power-manager.github.io
  resources:
  - powerconfigs
  - powerprofiles
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - power.cluster-power-manager.github.io
  resources:
  - powerconfigs/status
  - powernodestates/status
  verbs:
  - get
  - patch
- apiGroups:
  - power.cluster-power-manager.github.io
  resources:
  - powernodeconfigs
  - uncores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - power.cluster-power-manager.github.io
  resources:
  - powernodestates
  verbs:
  - create
  - delete
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-agent-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - power.cluster-power-manager.github.io
  resources:
  - powernodeconfigs
  - powernodestates
  - powerprofiles
  - uncores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - power.cluster-power-manager.github.io
  resources:
  - powernodestates/status
  verbs:
  - get
  - patch
