# Following example of: https://github.com/openshift/enhancements/blob/master/hack/Dockerfile.markdownlint
FROM fedora:latest
WORKDIR /workdir
RUN dnf install -y git golang
COPY install-markdownlint.sh /tmp
RUN /tmp/install-markdownlint.sh
ENTRYPOINT ["/workdir/hack/markdownlint.sh"]
